### ISSUE TITLE
Request: Navigation of interactive dotplot

### ISSUE THREAD

**Issue by aakashsur** [MariaNattestad/Assemblytics_web#1]
Great project and awesome site. One request - a good way of navigating the interactive dotplot. Maybe the inclusion of a return to all by all view, and potentially a drag and zoom type functionally?

**Comment by MariaNattestad** [comment]
Currently, you can right-click to zoom all the way back out. There is no drag to zoom functionality because I chose to make dragging cause panning instead, which allows you to see nearby regions without zooming all the way back out and reselecting the region. It is a tradeoff in functionality, but I appreciate your ideas and will try to incorporate a way to switch between drag-to-pan and drag-to-zoom functionalities in the future. Thanks!
